# Generated by Django 4.2a1 on 2023-02-08 10:46

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("tlg_id", models.IntegerField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=32)),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(blank=True, max_length=64)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
                ),
            ],
            options={
                "verbose_name": "TelegramUser",
            },
        ),
        migrations.AlterModelOptions(
            name="adminuser",
            options={"verbose_name": "DB User"},
        ),
    ]
