# Generated by Django 4.2.1 on 2023-05-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_remoteimage_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="remoteimage",
            name="remote_url",
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
