# Generated by Django 4.2b1 on 2023-03-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_account_card"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="card",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="card",
            name="value",
        ),
        migrations.AlterField(
            model_name="account",
            name="uniq_id",
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="Favourite",
            fields=[
                ("tlg_id", models.IntegerField(primary_key=True, serialize=False)),
                ("favourites", models.ManyToManyField(related_name="favs", to="app.user")),
            ],
            options={
                "verbose_name": "Favourite",
                "db_table": "fav_table",
            },
        ),
    ]
