# Generated by Django 4.2.1 on 2023-05-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_transaction_tx_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="already_show_flag",
            field=models.BooleanField(default=0),
        ),
    ]
