# Generated by Django 4.2.1 on 2023-05-17 17:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_transaction_already_show_flag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="already_show_flag",
            new_name="already_shown_flag",
        ),
    ]
